export const DEFAULT_AGENT_COMMAND_TIMEOUT_MS = 120_000;
export const MAX_AGENT_COMMAND_TIMEOUT_MS = 600_000;
export const MAX_AGENT_COMMAND_EXECUTABLE_BYTES = 1_024;
export const MAX_AGENT_COMMAND_ARGS = 64;
export const MAX_AGENT_COMMAND_ARG_BYTES = 8_192;
export const MAX_AGENT_COMMAND_ARGS_BYTES = 32_768;
export const MAX_AGENT_COMMAND_OUTPUT_BYTES = 32_768;
