import { execFile as execFileCallback } from "node:child_process";
import { copyFile, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { ownedTest } from "../../fixtures/owned-test-scope.js";

const execFile = promisify(execFileCallback);
const foundation = fileURLToPath(
  new URL("../../../native/verification-observer/", import.meta.url),
);
const harness = fileURLToPath(
  new URL("../../fixtures/observer-namespace-filter-harness.c", import.meta.url),
);
const linuxTarget = process.platform === "linux" && process.arch === "x64";

// Offline checks only: the filter is captured, never installed, and no namespace is created.
describe.skipIf(!linuxTarget)("observer namespace restriction filter", () => {
  it(
    "denies namespace creation and joining while allowing ordinary processes and threads",
    ownedTest(async (scope) => {
      const output = join(await scope.temporaryDirectory("flow-observer-filter-"), "harness");
      await execFile(
        "gcc",
        [
          "-O2",
          "-Wall",
          "-Wextra",
          "-Werror",
          "-I",
          join(foundation, "observer"),
          "-o",
          output,
          harness,
        ],
        { timeout: 60_000 },
      );
      const result = await execFile(output, [], { timeout: 10_000 });
      expect(JSON.parse(result.stdout)).toEqual({
        instructions: 18,
        failures: 0,
      });
    }),
    90_000,
  );

  it(
    "applies the observer patch exactly and compiles the patched helper without warnings",
    ownedTest(async (scope) => {
      const root = await scope.temporaryDirectory("flow-observer-patch-");
      const source = join(root, "observer-apply-seccomp.c");
      await copyFile(join(foundation, "upstream/apply-seccomp.c"), source);
      await execFile(
        "patch",
        [
          "--batch",
          "--forward",
          "--fuzz=0",
          "--no-backup-if-mismatch",
          source,
          join(foundation, "observer/apply-seccomp.patch"),
        ],
        { timeout: 10_000 },
      );
      const patched = await readFile(source, "utf8");
      expect(patched).toContain('#include "namespace-restriction.h"');
      // The restriction must be installed in the worker after trusted setup and before execvp.
      const restriction = patched.indexOf("install_namespace_restriction() < 0");
      expect(restriction).toBeGreaterThan(patched.indexOf("install_observe_filter(sp[1]);"));
      expect(restriction).toBeLessThan(patched.indexOf("execvp(command_argv[0], command_argv);"));
      // A stand-in header lets the helper compile; the real header is generated by build.sh.
      await writeFile(
        join(root, "unix-block-bpf.h"),
        "static const unsigned char unix_block_bpf[] = {0x06,0,0,0,0,0,0xff,0x7f};\n",
      );
      await execFile(
        "gcc",
        [
          "-O2",
          "-Wall",
          "-Wextra",
          "-Werror",
          "-I",
          join(foundation, "observer"),
          "-I",
          root,
          "-c",
          source,
          "-o",
          join(root, "observer-apply-seccomp.o"),
        ],
        { timeout: 60_000 },
      );
    }),
    90_000,
  );
});
